steps:
  - command: |
        echo "+++ :hammer: Building" && \
        ./scripts/eosio_build.sh -y && \
        echo "--- :compression: Compressing build directory" && \
        tar -pczf build.tar.gz build/
    label: ":aws: 2 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_2-2"
        workdir: /data/job
    timeout: 60

  - wait

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":aws: 2 Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        ~/bin/mongod --fork --dbpath ~/data/mongodb -f ~/etc/mongod.conf --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && PATH=\$PATH:~/opt/mongodb/bin ~/bin/ctest -j8 -LE _tests --output-on-failure
    label: ":aws: 2 Tests"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_2-2"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":aws: 2 Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        ~/bin/mongod --fork --dbpath ~/data/mongodb -f ~/etc/mongod.conf --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && PATH=\$PATH:~/opt/mongodb/bin ~/bin/ctest -L nonparallelizable_tests --output-on-failure
    label: ":aws: 2 NP Tests"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_2-2"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":aws: 2 Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -L long_running_tests --output-on-failure
    label: ":aws: 2 LR Tests"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_2-2"
        workdir: /data/job
    timeout: 90